apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: frontend
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: gcr.io/mark-test-178322/front-service:latest
          name: front-service
          ports:
            - containerPort: 8080
        - image: gcr.io/mark-test-178322/sidecar-service:latest
          name: sidecar-service
          ports:
            - containerPort: 8081